name: build

on:
  push:
    branches:
      - main
      - 'renovate/**'

  pull_request:

  schedule:
    - cron: '0 1 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          show-progress: false

      - name: Init
        run: ./bin/init.sh

  build:
    runs-on: ubuntu-latest
    needs:
      - setup

    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64
        node-version:
          - 20.10.0

    env:
      ARCH: ${{ matrix.arch }}
      NODE_VERSION: ${{ matrix.node-version }}
      BUILDKIT_PROGRESS: plain
      BUILDX_NO_DEFAULT_LOAD: 1

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          show-progress: false

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: build for ${{ matrix.node-version }} ${{ matrix.arch }}
        run: ./bin/build.sh

      - name: Save artifacts
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: binaries
          if-no-files-found: error
          path: |
            ./cache/*.br

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          show-progress: false

      - name: Download artifacts
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: binaries
          path: .cache

      - uses: ncipollo/release-action@a2e71bdd4e7dab70ca26a852f29600c98b33153e # v1.13.0
        if: env.DRY_RUN == 'false'
        with:
          allowUpdates: true
          body: See https://github.com/uhop/node-re2?tab=readme-ov-file#release-history for more changes
          commit: ${{ github.sha }}
          name: ${{ env.VERSION }}
          tag: v${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: .cache/**
