name: build

on:
  push:
    branches:
      - main
      - 'renovate/**'

  pull_request:

  schedule:
    - cron: '0 1 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    # lowest possible glibc version
    # TODO: use docker to build?
    runs-on: ubuntu-20.04

    strategy:
      # fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64
        node-version:
          - 20
          - 18

    env:
      ARCH: ${{ matrix.arch }}
      NODE_VERSION: ${{ matrix.node-version }}
      BUILDKIT_PROGRESS: plain
      BUILDX_NO_DEFAULT_LOAD: 1

    steps:
      - name: docker-config
        uses: containerbase/internal-tools@44cca769d0981f407b3eb21aa294efb2cdb6b262 # v3.0.36
        with:
          command: docker-config

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          show-progress: false

      - name: Init
        run: ./bin/init.sh

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies for ${{ matrix.arch }}
        if: matrix.arch == 'aarch64'
        run: |
          sudo apt-get update -qq
          sudo apt-get -q install -qq -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu binutils-aarch64-linux-gnu

      - name: Build for Node ${{ matrix.node-version }}
        run: ./bin/build.sh

      - name: Save artifacts
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: binaries
          if-no-files-found: error
          path: |
            .cache/*.br

  build-success:
    runs-on: ubuntu-latest
    needs:
      - build
    timeout-minutes: 1
    if: always()
    steps:
      - name: Fail for failed or cancelled builds
        if: |
          needs.build.result == 'failure' ||
          needs.build.result == 'cancelled'
        run: exit 1

  release:
    needs: build-success
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          show-progress: false

      - name: Init
        run: ./bin/init.sh

      - name: Download artifacts
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: binaries
          path: .cache

      - uses: ncipollo/release-action@6c75be85e571768fa31b40abf38de58ba0397db5 # v1.13.0
        if: github.ref_name == 'main'
        with:
          allowUpdates: true
          body: See https://github.com/uhop/node-re2#release-history for more changes
          commit: ${{ github.sha }}
          name: ${{ env.VERSION }}
          tag: ${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: .cache/*.*
